#...............................................................................
#
#  This file is part of the Doxyrest toolkit.
#
#  Doxyrest is distributed under the MIT license.
#  For details see accompanying license.txt file,
#  the public copy of which is also available at:
#  http://tibbo.com/downloads/archive/doxyrest/license.txt
#
#...............................................................................

dist:      xenial
osx_image: xcode11.3
language:  cpp

os:
    - linux
    - osx

compiler:
    - gcc
    - clang

env:
    global:
        - secure: GTOooOAI5LUCGn4sf4G0V/un4bWYyaL8RC+tqiF3WAuHJJcFf66qz++loWE91RPSVpt7div0NyHcSvQbMhkBSmDvztIFOI0Eo9G3QjtIemdBTSME8pfIa/7ftSmmqwQeDOm4FsUdCdNIW5DDsbyQL9iba9q9T+dME9DatcpNaqTKKU4PKLWHwQpKYgzHL5FdhJK9d071Fpp9cKC1oB11RJERiJ7Lpl1TKumoYhts+yTRciE1dGFiLmW6mssn0opaKhE1fxI4i7RcZN+Zu1XdYwDRq645CWrAC42Gk/4xr6Kk2GwgG7ZzF1ObjOuJRO4aHvUjAY5YzwqlmlTVRaDnDGVWvw46EZ/QwNZ5NihX+6UqBFZtai7ggFXkblaobtHCTjymz/3rNjUSomPRjhQKU7jxG3mJgOMeOE8gy9t/PjOqcgenGugujb2/OgOha9y5xtcxWkkRXv5iqD4LPUIC7FISBugO/DDKNEs4iatnaWd0CYNUMFyxqlTk/W5UrBVUR1jd16z0jC+bporq47DYS72gBEvnTt2KE63CpH7ClHEkzl9qs0kjZAjKULgtxGLvKZy+iddRz1dF00+aNBFBYwOCzTZa2t/O7GTCxxgzIHk9w4zbxotJRidMoB+WCx7CEpNyQMGjy0m0Zgyc7FfohMdojMd7cg0RkuI3jhv/1f8=

    matrix:
        - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
        - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release
        - TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
        - TARGET_CPU=x86 BUILD_CONFIGURATION=Release

matrix:
    exclude:
        - os:       osx
          compiler: gcc

        - os:  osx
          env: TARGET_CPU=x86 BUILD_CONFIGURATION=Debug

        - os:  osx
          env: TARGET_CPU=x86 BUILD_CONFIGURATION=Release

install:
    - source ci/travis/set-env.sh
    - bash ci/travis/install-$TRAVIS_OS_NAME.sh
    - git clone --depth 1 https://github.com/vovkos/axl
    - git clone --depth 1 https://github.com/vovkos/graco
    - git clone --depth 1 https://github.com/vovkos/luadoxyxml

script:
    - bash -e ci/travis/build.sh
    - source ci/travis/get-package-file-name.sh

notifications:
    webhooks:
        on_success: always
        on_failure: never
        on_error:   never
        on_cancel:  never

        urls:
            - http://jancy.org:5005/travis-ci

deploy:
    -   provider:      pages
        skip_cleanup:  true
        local_dir:     build/doc/html
        github_token:  $GITHUB_TOKEN

        on:
            branch:    master
            condition: $BUILD_DOC == ON

    -   provider:     releases
        file:         $DOXYREST_PACKAGE_FILE

        skip_cleanup: true
        overwrite:    true

        api_key:
            secure:   eFpWPF/1P1+DbHChlENnddunj4L8wdHHZvFUZoGXHwUgQ3xvo1CdKRtBo3Sv0HYftTlQjSrqCozx2tlunz9tNr6vKwLor7056MpqjmQsrujCVHhq1TsZd409ZkVR/3Dcl26yx6MMjVm43n6GAx3xLNna5hamq/G/7KggmAoJfWyT3bti4IIQrUw1w57Diyg1m778mXinAsKxy4IHFZR8LrxYKaNO4fATGBwNKJ3JUcTaE4Dap1IgDL8Mqu7c286ipzRFlJtTxRJPsMc3OkfSzgKQ2U7kfhU1pnRDEgd0D59MdUnU+4IZ5nQpbtNJejiEtozLz5YojKtDcvWEKujEQ/7bphEn/XwbCgH6dP6pximFvGphSCoKMjRkIqPN6oK1dQ7se63cCxNrc6r8/6C4GOIqrGQXf+7XCPLh2kdwJzOVG7fDvDWtd88szObROSWURBuMnxc3UP5WyS7zWkdgMMwIfuk96ZOwuRhdAWQ3K0/iHTK6PpCotGNqwKawJtgTj1v2mYXLoiecTbeKZ3ixfKlQX0XN5mx7/5kYKh5X0OGKgV7eTBSFF9Uc7gCjKld4vWrcTmi8V3OiZ5bzm+UGpWdIys3gHbE8sjVT3qvFuikyegfWniRDdvSWmcJrBm5/lIA9VjovapXmnQu3CAQ5MrzJp0QeDWArkmDjeeJMjZI=

        on:
            branch:    master
            tags:      true
            condition: $BUILD_PACKAGE == ON
